import { Figtree } from 'next/font/google'
import "./globals.css";
import SessionAuthProvider from '@/context/auth-provider';


const inter = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Henry Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main>
          <SessionAuthProvider>
              {children}
          </SessionAuthProvider>
        </main>
      </body>
    </html>
  );
}
