import { Figtree } from 'next/font/google'
import "./globals.css";
import SessionAuthProvider from '@/components/auth-provider';
import ModalProvider from '@/providers/ModalProvider';
import ToasterProvider from '@/providers/ToasterProvider';


const inter = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Henry Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
          <SessionAuthProvider>
            <ToasterProvider />
            <ModalProvider />
        <main>
            {children}
        </main>
          </SessionAuthProvider>
      </body>
    </html>
  );
}
