import { Figtree } from 'next/font/google'
import SidebarAdmin from '@/components/admin/SidebarAdmin';

const inter = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Henry Music",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className={`${inter.className} flex flex-col w-full h-screen gap-4 p-2 box-border`}>
        <SidebarAdmin>
          {children}
        </SidebarAdmin>
      </div>
  );
}
